# Generated by Django 4.2.30 on 2026-05-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chap_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('chap_name', models.CharField(max_length=50)),
                ('chap_datetime', models.DateTimeField()),
                ('chap_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('choice_detail', models.CharField(max_length=200)),
                ('choice_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.CreateModel(
            name='detail_exam_set',
            fields=[
                ('detail_exam_set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qt_order', models.IntegerField(max_length=3)),
            ],
            options={
                'db_table': 'detail_exam_set',
            },
        ),
        migrations.CreateModel(
            name='Exam_set',
            fields=[
                ('exam_set_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('exam_set_header', models.TextField()),
                ('exam_set_detail', models.TextField()),
            ],
            options={
                'db_table': 'exam_set',
            },
        ),
        migrations.CreateModel(
            name='Online_exam',
            fields=[
                ('online_exam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('online_exam_name', models.CharField(max_length=150)),
                ('online_exam_pass', models.CharField(max_length=20)),
                ('online_exam_is_active', models.BooleanField(default=False)),
                ('online_exam_create', models.DateTimeField(auto_now_add=True)),
                ('exam_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam_set')),
            ],
            options={
                'db_table': 'online_exam',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qt_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('qt_detail', models.TextField()),
                ('qt_diff_lv', models.CharField(max_length=10)),
                ('chap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='result_exam',
            fields=[
                ('result_exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('result_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_exam', models.DateTimeField()),
                ('status_exam', models.CharField(max_length=20)),
                ('detail_exam_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detail_exam_set')),
                ('online_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.online_exam')),
            ],
            options={
                'db_table': 'result_exam',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.IntegerField(primary_key=True, serialize=False)),
                ('online_exam_id', models.CharField(blank=True, max_length=50, null=True)),
                ('std_name', models.CharField(max_length=100)),
                ('std_email', models.CharField(max_length=100)),
                ('std_pass', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=100)),
                ('t_email', models.CharField(max_length=100)),
                ('t_pass', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sj_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sj_name', models.CharField(max_length=100)),
                ('sj_datetime', models.DateTimeField()),
                ('sj_desc', models.CharField(max_length=200)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='std_answer',
            fields=[
                ('ans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ans', models.IntegerField()),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.choice')),
                ('qt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('result_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.result_exam')),
            ],
            options={
                'db_table': 'std_answer',
            },
        ),
        migrations.AddField(
            model_name='result_exam',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='online_exam',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='exam_set',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.CreateModel(
            name='diff_index',
            fields=[
                ('diff_index_id', models.IntegerField(primary_key=True, serialize=False)),
                ('diff_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('detail_exam_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detail_exam_set')),
                ('qt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
            options={
                'db_table': 'diff_index',
            },
        ),
        migrations.CreateModel(
            name='detail_online_exam',
            fields=[
                ('detail_online_exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_exam', models.DateField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('online_exam_status', models.CharField(max_length=20)),
                ('num_of_std', models.IntegerField()),
                ('online_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.online_exam')),
            ],
            options={
                'db_table': 'detail_online_exam',
            },
        ),
        migrations.AddField(
            model_name='detail_exam_set',
            name='exam_set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam_set'),
        ),
        migrations.AddField(
            model_name='detail_exam_set',
            name='qt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='qt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='sj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
    ]
