# Generated by Django 4.2.30 on 2026-05-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='sj_id',
            field=models.ForeignKey(db_column='sj_id', on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='qt_id',
            field=models.ForeignKey(db_column='qt_id', on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='detail_exam_set',
            name='exam_set_id',
            field=models.ForeignKey(db_column='exam_set_id', on_delete=django.db.models.deletion.CASCADE, to='api.exam_set'),
        ),
        migrations.AlterField(
            model_name='detail_exam_set',
            name='qt_id',
            field=models.ForeignKey(db_column='qt_id', on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='detail_online_exam',
            name='online_exam_id',
            field=models.ForeignKey(db_column='online_exam_id', on_delete=django.db.models.deletion.CASCADE, to='api.online_exam'),
        ),
        migrations.AlterField(
            model_name='exam_set',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='online_exam',
            name='exam_set_id',
            field=models.ForeignKey(db_column='exam_set_id', on_delete=django.db.models.deletion.CASCADE, to='api.exam_set'),
        ),
        migrations.AlterField(
            model_name='online_exam',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chap_id',
            field=models.ForeignKey(db_column='chap_id', on_delete=django.db.models.deletion.CASCADE, to='api.chapter'),
        ),
        migrations.AlterField(
            model_name='result_exam',
            name='online_exam_id',
            field=models.ForeignKey(db_column='online_exam_id', on_delete=django.db.models.deletion.CASCADE, to='api.online_exam'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
