# Generated by Django 4.2.30 on 2026-05-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chapter_sj_id_alter_choice_qt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff_index',
            name='detail_exam_set_id',
            field=models.ForeignKey(db_column='detail_exam_set_id', on_delete=django.db.models.deletion.CASCADE, to='api.detail_exam_set'),
        ),
        migrations.AlterField(
            model_name='diff_index',
            name='qt_id',
            field=models.ForeignKey(db_column='qt_id', on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='result_exam',
            name='detail_exam_set_id',
            field=models.ForeignKey(db_column='detail_exam_set_id', on_delete=django.db.models.deletion.CASCADE, to='api.detail_exam_set'),
        ),
        migrations.AlterField(
            model_name='result_exam',
            name='std_id',
            field=models.ForeignKey(db_column='std_id', on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='std_answer',
            name='choice_id',
            field=models.ForeignKey(db_column='choice_id', on_delete=django.db.models.deletion.CASCADE, to='api.choice'),
        ),
        migrations.AlterField(
            model_name='std_answer',
            name='result_exam_id',
            field=models.ForeignKey(db_column='result_exam_id', on_delete=django.db.models.deletion.CASCADE, to='api.result_exam'),
        ),
    ]
