# Generated by Django 4.2.30 on 2026-07-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_std_id_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='qt_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_text', models.TextField(blank=True, null=True)),
                ('shared_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'db_table': 'question_group',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group_id',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.questiongroup'),
        ),
    ]
