# Generated by Django 4.2.30 on 2026-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_choice_choice_image_url_question_qt_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_detail',
            field=models.TextField(),
        ),
    ]
