# Generated by Django 4.2.30 on 2026-07-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_choice_choice_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_answer',
            name='qt_id',
            field=models.ForeignKey(db_column='qt_id', on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
    ]
