# Generated by Django 4.2.30 on 2026-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_std_answer_qt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_exam',
            name='exam_type',
            field=models.CharField(default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='qt_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
