# Generated by Django 4.2.30 on 2026-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_online_exam_exam_type_alter_question_qt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online_exam',
            name='exam_type',
        ),
        migrations.AlterField(
            model_name='student',
            name='std_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
